- name: Install Applications
  become: true
  apt:
    pkg:
      - aptitude
      - arandr
      - caffeine
      - cargo
      - compton
      - curl
      - dunst
      - exfat-fuse
      - exfat-utils
      - flameshot
      - fzf
      - highlight
      - htop
      - httpie
      - hub
      - i3
      - jmtpfs
      - jq
      - lxappearance
      - mtp-tools
      - nautilus
      - ncdu
      - neofetch
      - net-tools
      - nvidia-prime
      - orage
      - pavucontrol
      - powertop
      - qalculate
      - rofi
      - scrot
      - screen
      - slack
      - stow
      - surfraw
      - tig
      - tilix
      - tlp
      - tmux
      - tmuxinator
      - unclutter
      - virtualbox
      - w3m
      - w3m-img
      - wget
      - xautolock
      - xcb
      - zeal
